baseURL = "https://mactep.github.io/"
disablePathToLower = true
languageCode = "en-us"
title = "mactep.github.io"

theme = "PaperMod"

# header links
[[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 10

[[menu.main]]
identifier = "categories"
name = "categories"
url = "/categories/"
weight = 10

# using chroma for syntax highlighting
pygmentsUseClasses = true

[params.assets]
disableHLJS = true

[markup.highlight]
codeFences = true
guessSyntax = true
lineNos = false
style = "catppuccin-mocha"

# PaperMod settings
[params]
defaultTheme = "auto"
showCodeCopyButtons = true

[params.profileMode]
enable = false

[params.editPost]
URL = "https://github.com/mactep/mactep.github.io/content"
text = "Suggest Changes"
appendFilePath = true

